import baseConfig, { theme as _theme } from '@repo/configs/tailwind';
import { fonts, spacing as _spacing } from './uiConfig.js';

export default {
  ...baseConfig,
  theme: {
    ..._theme,
    extend: {
      ...(_theme?.extend || {}),
      colors: {
        ...(_theme?.extend?.colors || {}),
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
        "destructive-foreground": "var(--destructive-foreground)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        "chart-1": "var(--chart-1)",
        "chart-2": "var(--chart-2)",
        "chart-3": "var(--chart-3)",
        "chart-4": "var(--chart-4)",
        "chart-5": "var(--chart-5)",
        sidebar: "var(--sidebar)",
        "sidebar-foreground": "var(--sidebar-foreground)",
        "sidebar-primary": "var(--sidebar-primary)",
        "sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
        "sidebar-accent": "var(--sidebar-accent)",
        "sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
        "sidebar-border": "var(--sidebar-border)",
        "sidebar-ring": "var(--sidebar-ring)",
      },
      fontSize: {
        ...(_theme?.extend?.fontSize || {}),
        md: fonts.size.md,
        lg: fonts.size.lg,
        xl: fonts.size.xl,
        "2xl": fonts.size["2xl"],
        "4xl": fonts.size["4xl"],
      },
      spacing: {
        ...(_theme?.extend?.spacing || {}),
        "section-y": _spacing.sectionY.default,
        "section-y-lg": _spacing.sectionY.lg,
        "section-y-xl": _spacing.sectionY.xl,
        "section-x": _spacing.sectionX.default,
        "section-x-lg": _spacing.sectionX.lg,
        "section-x-xl": _spacing.sectionX.xl,
        "section-gap": _spacing.sectionGap.default,
        "section-gap-lg": _spacing.sectionGap.lg,
        "section-gap-xl": _spacing.sectionGap.xl,
      },
    },
  },
  content: [
    './app/**/*.{js,ts,jsx,tsx,html}',
    './components/**/*.{js,ts,jsx,tsx,html}',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx,html}',
  ],
};