import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles.css";
import Header from "@repo/ui/layouts/header/default";
import { dataConfig } from "./data/dataConfig";
import GridFooter from "@repo/ui/layouts/footer/GridFooter";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerFixed = true; 

  return (
    <html lang="en" className="light scroll-smooth scroll-p-10">
      <body
        className={`${geistSans.variable} ${geistMono.variable} overflow-x-hidden`}
      >
        <Header data={dataConfig.headerData} fixed={headerFixed} />

        <div
          className={`${headerFixed ? "pt-[75px]" : ""}`}
        >
          {children}
        </div>

        <GridFooter data={dataConfig.footer}/>
      </body>
    </html>
  );
}
