import type { Metadata } from "next";
import localFont from "next/font/local";
import "@repo/ui/globals.css";
import { Footer } from "@repo/ui/layouts/footer/footer";
import Header from "@repo/ui/layouts/header/default";
import { dataConfig } from "./data/dataConfig";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerFixed = true; 

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} overflow-x-hidden`}
      >
        <Header data={dataConfig.headerData} fixed={headerFixed} />

        <div
          className={`container ${headerFixed ? "pt-[75px]" : ""}`}
        >
          {children}
        </div>

        <Footer />
      </body>
    </html>
  );
}
