name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main, dev ]

jobs:
  # 1. Setup & Build Dependencies
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Cache Turborepo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: npm ci

      # КРИТИЧЕСКИ ВАЖНО: Собираем пакеты первыми
      - name: Build internal packages
        run: npm run build

      # Кешируем node_modules и собранные пакеты для других джобов
      - name: Cache build artifacts
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
            apps/*/node_modules
            packages/*/node_modules
            packages/*/dist
            .turbo
          key: build-${{ runner.os }}-${{ github.sha }}

  # 2. Lint (параллельно после setup)
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Restore build artifacts
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            apps/*/node_modules
            packages/*/node_modules
            packages/*/dist
            .turbo
          key: build-${{ runner.os }}-${{ github.sha }}

      - name: ESLint
        run: npm run lint

  # 3. Type Check (параллельно после setup)
  typecheck:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Restore build artifacts
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            apps/*/node_modules
            packages/*/node_modules
            packages/*/dist
            .turbo
          key: build-${{ runner.os }}-${{ github.sha }}

      - name: Type-Check
        run: npm run check-types

  # 4. Test (параллельно после setup)
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Restore build artifacts
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            apps/*/node_modules
            packages/*/node_modules
            packages/*/dist
            .turbo
          key: build-${{ runner.os }}-${{ github.sha }}

      - name: Run Vitest
        run: npm test

  # 5. Final Build Check (только если все остальное прошло)
  build-check:
    needs: [ lint, typecheck, test ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Restore build artifacts
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            apps/*/node_modules
            packages/*/node_modules
            packages/*/dist
            .turbo
          key: build-${{ runner.os }}-${{ github.sha }}

      - name: Verify Build
        run: npm run build